### ISSUE TITLE
npr.login() crashes immediately after reinstall

### ISSUE THREAD

**Issue by perrydc** [perrydc/npr#19]
>>> npr.login()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/dperry/anaconda/lib/python3.6/site-packages/npr/__init__.py", line 91, in login
    tokenData = {'client_id':config['id'],'client_secret':config['secret'],'code':deviceCodeJson['device_code'],'grant_type':'device_code'}
KeyError: 'device_code'

**Comment by perrydc** [comment]
not replicated with fix to previous bug
