### ISSUE TITLE
Permission Denied...

### ISSUE THREAD

**Issue by fondoger** [perrydc/npr#6]
when I use **npr.auth()**, and followed instructions, I got this error:
My environment: windows 10, python 3.6
```
app ID and/or app secret is missing.  Try npr.clientauth() or npr.auth() to access user data
To authenticate your app:
  1. LOGIN to http://dev.npr.org (if it's your first time, you'll need to register.)
  2. Open the dev console (drop down in the top right corner of dev center)
  3. Create a new application
  4. Select that application and enter your credentials below
Application ID:MyID
Application Secret:MyKey
Traceback (most recent call last):
  File "npr_youth_radio.py", line 2, in <module>
    npr.auth()
  File "C:\Program Files\Python36\lib\site-packages\npr-1.2.0-py3.6.egg\npr\__init__.py", line 42, in auth
    f=open(configfile,'w+')
PermissionError: [Errno 13] Permission denied: 'C:\\Program Files\\Python36\\lib\\site-packages\\npr-1.2.0-py3.6.egg\\npr\\npr.conf'

Press any key to continue . . .
```

**Comment by perrydc** [comment]
Looks like you just need to add read/write permissions to the npr.conf file, which stores your credentials.

I don't know how to force file permissions from a python script (usually this happens automatically based on the python setup), but happy to reopen if you have an idea.
